name: ci-documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          cache-dependency-glob: "docs/**"
          python-version: "cpython-3.9.21-linux-x86_64-gnu"

      - name: Install mkdocs deps
        run: |
          uv sync --only-group doc

      - name: Deploy Docs
        run: |
          uv run mkdocs gh-deploy --force --remote-branch gh-pages