name: publish-pypi

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check_build_trigger:
    name: Check build trigger
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.check_build_trigger.outputs.build }}
    steps:
      - name: Checkout auto-sklong
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: check_build_trigger
        name: Run check_build_trigger.sh
        run: bash build_tools/github/check_build_trigger.sh

  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          python-version: "cpython-3.9.21-linux-x86_64-gnu"

      - name: Lock & Sync All Dependencies
        run: |
          uv lock
          uv sync --all-groups

      - name: Run Tests Unit
        run: |
          uv run pytest -sv tests/unit

  pypi-publish:
    name: ☁️ upload release to TestPyPI
    runs-on: ubuntu-latest
    needs: [ check_build_trigger, unit_testing ]
    if: |
      always() &&
      needs.check_build_trigger.outputs.build &&
      needs.unit_testing.result == 'success'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          python-version: "cpython-3.9.21-linux-x86_64-gnu"

      - name: Lock & Sync for Release
        run: |
          uv lock
          uv sync --all-groups

      - name: Build distribution
        run: |
          uv build

      - name: Publish package to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv publish