name: pytest
on:
  workflow_dispatch:
  pull_request:

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout this repository
        uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          architecture: x64
          prerelease: false
          enable-pep582: true

      - name: Install dependencies from pdm.lock
        run: |
          pdm install --dev

      - name: Run tests
        run: pdm run tests_unit

  system:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout this repository
        uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          architecture: x64
          prerelease: false
          enable-pep582: true

      - name: Install dependencies from pdm.lock
        run: |
          pdm install --dev

      - name: Run tests
        run: pdm run tests_system
