name: ci-tests

on:
  workflow_dispatch:
  pull_request:


permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          python-version: "cpython-3.9.21-linux-x86_64-gnu"

      - name: Lock & Sync All Dependencies
        run: |
          uv lock
          uv sync --all-groups

      - name: Run Tests Unit
        run: |
          uv run pytest -sv tests/unit

      - name: Run Tests System
        run: |
          uv run pytest -sv tests/system