name: Test --pre

on:
  workflow_dispatch:
  schedule:
    - cron: "00 0 * * 1"

jobs:
  unit:
    name: Run tests with prereleases
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9.21"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv & Python
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
          python-version: "cpython-3.9.21-linux-x86_64-gnu"

      - name: Lock dependencies with pre-releases
        run: |
          uv lock --prerelease allow

      - name: Sync All Groups
        run: |
          uv sync --all-groups

      - name: Run tests
        run: |
          uv run pytest -sv tests/unit